### ISSUE TITLE
Request: Enable firefox desktop file translation

### ISSUE THREAD

**Issue by wsxy162** [openSUSE/desktop-file-translations#12]
Firefox packagers need to include a desktop file since upstream mozilla doesn't provide one. The source desktop file name is MozillaFirefox.desktop and then change to firefox.desktop after packaging.
 
Could update-desktop-files-apps.po include this desktop file?

**Comment by lkocman** [comment]
Done, translation for Leap 15.6 had firefox on input. We did drop the appdata/appstream in the end, but the firefox.desktop and mime/packages/firefox.xml were included.

```
lkocman@localhost:~/Workspace/opensuse/desktop-file-translations/51-xml> grep -i mozillafirefox matched_files.txt 
./x86_64/MozillaFirefox-115.4.0-150200.152.114.1.x86_64.rpm:    -rw-r--r--    1 root    root                     9712 Oct 23 08:21 /usr/share/applications/firefox.desktop
./x86_64/MozillaFirefox-115.4.0-150200.152.114.1.x86_64.rpm:    -rw-r--r--    1 root    root                     2163 Oct 23 08:21 /usr/share/metainfo/firefox.appdata.xml
./x86_64/MozillaFirefox-115.4.0-150200.152.114.1.x86_64.rpm:    -rw-r--r--    1 root    root                      292 Oct 23 08:21 /usr/share/mime/packages/firefox.xml

```

**Comment by lkocman** [comment]
https://github.com/openSUSE/desktop-file-translations/pull/14
