### ISSUE TITLE
Run msgmerge with --previous

### ISSUE THREAD

**Issue by elchevive** [openSUSE/desktop-file-translations#3]
Hi,

Could you add --previous to msgmerge command? This way a change in a string that became fuzzy is highlighted on Weblate (or other po editor):

https://docs.weblate.org/en/latest/faq.html

> Can Weblate highlight change in a fuzzy string?
> 
> Weblate supports this, however it needs the data to show the difference.
> 
> For Gettext PO files, you have to pass parameter --previous to msgmerge when updating PO files, for example:
> 
> msgmerge --previous -U po/cs.po po/phpmyadmin.pot
> For monolingual translations, Weblate can find the previous string by ID, so it shows the differences automatically.

**Comment by Vogtinator** [comment]
PR accepted, marking as fixed.
