### ISSUE TITLE
FILENAME_PATTERNS is a dict

### ISSUE THREAD

**Issue by lnussel** [openSUSE/desktop-file-translations#6]
FILENAME_PATTERNS is a dict so the 'catch all' rule that is meant as fallback may actually match first, resulting in quite a lot in the main desktop file file.

**Comment by Vogtinator** [comment]
That's not an issue from Python 3.6 onwards: https://stackoverflow.com/a/39537308

If it has to work with older versions, I can change it.

**Comment by lnussel** [comment]
well, I guess it's fine to require something new here but we need a check to avoid the mistake I made :)
